### ISSUE TITLE
Comparison to PMTiles

### ISSUE THREAD

**Issue by tordans** [versatiles-org/versatiles-converter#2]
Hey Michael, unfortunately I missed you presentation on Monday at MapTime Berlin. I was wondering how your project compares to the relatively new but relatively well integrated and adopted PMTiles Project?

About PMTiles:
* https://protomaps.com/blog/serverless-maps-now-open-source
* https://www.openstreetmap.org/user/rtnf/diary/400836

**Comment by tordans** [comment]
@MichaelKreil FYI I saw https://twitter.com/protomaps/status/1635697842613551105 by the person behind PMTiles and there will be a meetup https://www.eventbrite.com/e/geoberlin-april-2023-tickets-591187195817. This might be a good chance to chat.

**Comment by snuup** [comment]
closed but unanswered.

**Comment by MichaelKreil** [comment]
https://github.com/versatiles-org/versatiles-rs/issues/24
